name: Build and deploy Node.js app to Azure Web App - linktree

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step for installing frontend dependencies (React app)
      - name: Install frontend dependencies
        run: |
          cd server/client
          npm install

      - name: Build frontend
        run: |
          cd server/client
          npm run build

      # Step for installing backend dependencies (Node.js app)
      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Build backend
        run: |
          cd server
          npm run build

      # Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            server/client/build
            server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_308818202E4A46BCB41523A66A360575 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_74005A045BAD4AC69495999B5131392B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONIDC888967D2C39499CB2D8A0154B0E5791 }}

      # Deploy frontend to Azure Web App (React)
      - name: Deploy to Azure Web App (Frontend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'linktree-frontend'
          slot-name: 'Production'
          package: ./server/client/build

      # Deploy backend to Azure Web App (Node.js)
      - name: Deploy to Azure Web App (Backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'linktree-backend'
          slot-name: 'Production'
          package: ./server
